/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package name.dougmcneil.plsql.ui;

import java.awt.Dialog;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import name.dougmcneil.plsql.PLSQLDriver;
import name.dougmcneil.plsql.PLSQLNodeProvider;
import org.openide.util.NbBundle;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.Lookup;

/**
 *
 * @author doug
 */
public class PLSQLPropertiesPanel extends javax.swing.JPanel {

    private DialogDescriptor _descriptor;
    
    /**
     * Creates new form SQLPropertiesPanel
     */
    public PLSQLPropertiesPanel() {
        initComponents();
    }

    public static boolean showPLSQLProperties() {
        assert SwingUtilities.isEventDispatchThread();

        PLSQLPropertiesPanel panel = new PLSQLPropertiesPanel();
        String title = NbBundle.getMessage(PLSQLPropertiesPanel.class, "LBL_PropertiesPanel");

        DialogDescriptor desc = new DialogDescriptor(panel, title);
        desc.createNotificationLineSupport();

        for (;;) {
            Dialog dialog = DialogDisplayer.getDefault().createDialog(desc);


            String acsd = NbBundle.getMessage(PLSQLPropertiesPanel.class, "LBL_PropertiesPanel");
            dialog.getAccessibleContext().setAccessibleDescription(acsd);
            dialog.setVisible(true);
            dialog.dispose();

            if (!DialogDescriptor.OK_OPTION.equals(desc.getValue())) {
                return false; // NOI18N
            }

            PLSQLDriver.getInstance().setJarPath(
                    panel.jTextFieldJarLocation.getSelectedText());
            
            PLSQLDriver.getInstance().init();
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelJarLocation = new javax.swing.JLabel();
        jTextFieldJarLocation = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabelTitle, org.openide.util.NbBundle.getMessage(PLSQLPropertiesPanel.class, "PLSQLPropertiesPanel.jLabelTitle.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabelJarLocation, org.openide.util.NbBundle.getMessage(PLSQLPropertiesPanel.class, "PLSQLPropertiesPanel.jLabelJarLocation.text")); // NOI18N

        jTextFieldJarLocation.setToolTipText(org.openide.util.NbBundle.getMessage(PLSQLPropertiesPanel.class, "PLSQLPropertiesPanel.jTextFieldJarLocation.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButtonBrowse, org.openide.util.NbBundle.getMessage(PLSQLPropertiesPanel.class, "PLSQLPropertiesPanel.jButtonBrowse.text")); // NOI18N
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(0, 193, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelJarLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldJarLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBrowse)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJarLocation)
                    .addComponent(jTextFieldJarLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowse))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.setCurrentDirectory(null);
        chooser.setDialogTitle(NbBundle.getMessage(PLSQLPropertiesPanel.class, "LBL_FindFile"));
        chooser.setMultiSelectionEnabled(false);
        chooser.setSelectedFile(null);
        
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jTextFieldJarLocation.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JLabel jLabelJarLocation;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldJarLocation;
    // End of variables declaration//GEN-END:variables
}
